{% set name = "anthropic" %}
{% set version = "0.43.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/anthropics/anthropic-sdk-python/archive/v{{ version }}.tar.gz
  sha256: 8ccea015680a86edf51cadcefe7adca01d779c0b2c31113dbd4c649d8c545614

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - hatch-fancy-pypi-readme
    - hatchling
    - pip
  run:
    - typing_extensions >=4.10,<5
    - python >={{ python_min }},<4.0.0
    - httpx >=0.23.0,<1
    - pydantic >=1.9.0,<3
    - typing-extensions >=4.7,<5
    - anyio >=3.5.0,<5
    - distro >=1.7.0,<2
    - sniffio
    - cached-property
    - tokenizers >=0.13.0
    - jiter >=0.4.0,<1

test:
  imports:
    - anthropic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/anthropics/anthropic-sdk-python
  license: MIT
  license_file: LICENSE
  summary: Library for accessing the anthropic API
  doc_url: https://console.anthropic.com/docs

extra:
  recipe-maintainers:
    - jan-janssen
    - jenan-anthropic
    - mikelambert
    - moritzwilksch
    - siboehm
    - x5a
